# Note: I refuse to use flake.nix and home manager.
# Recover fix tip: boot into live iso, lsblk, sudo nixos-enter --root <Mounted_Device_Path>, su - asarra, (commands), exit
# Gems: https://github.com/gianarb/dotfiles/tree/12ab8fa01d3d8efd0e96f7287a2447df3013a17f https://github.com/NixOS/nixos-hardware
# 0. Grapical install first without swap. We'll add swap file later. This way we won't have to touch hardware-configuration.nix at all
# 1. sudo nixos-rebuild switch
# 2. Download and apply new config
# 3. sudo bash ./install.sh

{ config, pkgs, lib, ... }:

let
  user = { name = "asarra"; origin = "de"; time = "Europe/Berlin"; language = "en_US.UTF-8"; };
  device = { host = "guardian"; mode = "ondemand"; cores = 2; };
  inherit (lib) mkForce;
in
{
  imports = [
    ./hardware-configuration.nix # autogenerated
    ./nixfiles/environment.nix
    ./nixfiles/systemd.nix
  ];

  boot = {
    loader = { # Bootloader
      efi.canTouchEfiVariables = true;
      timeout = 5;
      grub = { # GRUB 2 > Systemd-boot
        enable = true;
        efiSupport = true;
        devices = ["nodev"];
        configurationLimit = 3;
        theme = builtins.fetchGit "https://github.com/HenriqueLopes42/themeGrub.CyberEXS"; # Man: https://nix.dev/manual/nix/2.23/language/builtins
        # More entries
        useOSProber = true;
        memtest86.enable = true;
        extraEntries = ''
            menuentry "Reboot" { reboot }
            menuentry "Power off" { halt }
            menuentry "BIOS" { fwsetup }
        '';
      };
    };

    # Kernel
    kernelPackages = pkgs.linuxPackages_hardened;
    kernelParams = [ "vfio-pci.ids=10de:1e84,10de:10f8" "amd_iommu=on" "iommu=pt" ] ++ [ "quiet" ] ++ [ "zswap.enabled=1" "zswap.max_pool_percent=25" "zswap.shrinker_enabled=1" ]; # https://www.kernel.org/doc/Documentation/admin-guide/kernel-parameters.txt
    kernelModules = [ "vfio_pci" "vfio" "vfio_iommu_type1" ] ++ config.boot.initrd.availableKernelModules ++ config.boot.initrd.kernelModules; # See: https://github.com/triton/triton
    kernel.sysctl = { "vm.swappiness" = 40; "vm.page-cluster" = 2; }; # swap specific kernel tunables
    blacklistedKernelModules = [ "nvidia" "nouveau" ];
    initrd.availableKernelModules = (lib.subtractLists ["sr_mod" "rtsx_pci_sdmmc"] config.boot.initrd.availableKernelModules); # No "sr_mod" (CDs) & "rtsx_pci_sdmmc" (m. SD cards) https://ryantm.github.io/nixpkgs/functions/library/lists
    initrd.verbose = false;
  };

  swapDevices = mkForce [{ device = "/swapfile"; size = 8192; }];
  powerManagement.cpuFreqGovernor = device.mode; # powersave, performance, ondemand

  networking = {
    hostName = device.host;
    networkmanager.enable = true; # Console: nmcli and nmtui
    useDHCP = mkForce true; #  I definitely want this
    nameservers = [ "9.9.9.9" "1.1.1.1" ]; # dns
    firewall = {
      allowPing = true;
    };
  };

  # Time zone, internationalisation, console mapping and fonts
  time.timeZone = user.time;
  i18n.defaultLocale = user.language;
  console.keyMap = user.origin;

  users = {
    users."${user.name}" = {
      isNormalUser = true;
      description = user.name;
      extraGroups = [ "networkmanager" "wheel" "libvirtd" ];
      home = "/home/${user.name}";
    };
  };

  nix = {
    optimise.automatic = true;
    gc.automatic = true; # automatic garbage collection
    gc.dates = "weekly";
    gc.options = "--delete-older-than 7d";
    settings = {
      auto-optimise-store = true; # finds duplicates and saves space
      cores = device.cores; # make -jX from Gentoo # https://github.com/NixOS/nix/issues/1127#issuecomment-412176841
      substituters = [ "https://nix-community.cachix.org" "https://cache.nixos.org/"]; # cache URLs of pre-built package binaries
      trusted-public-keys = [ "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=" ];
    };
  };

  security = {
    protectKernelImage = true;
    lockKernelModules = true;
    apparmor.enable = true;
    forcePageTableIsolation = true; # against meltdown and spectre attacks
    virtualisation.flushL1DataCache = "always";
  };

  system = {
    stateVersion = "24.05"; # Did you read the comment?
    nixos.tags = [ "" ]; # Adds a suffix to the generation label in GRUB. Think of this as a message in a git commit.
    autoUpgrade.enable = true;
    autoUpgrade.channel = "https://channels.nixos.org/nixos-24.05";
  };
}
