# Note: I refuse to use flake.nix and home manager.
# Recover fix tip: boot into live iso, lsblk, sudo nixos-enter --root <Mounted_Device_Path>, su - asarra, (commands), exit
# Gems: https://github.com/gianarb/dotfiles/tree/12ab8fa01d3d8efd0e96f7287a2447df3013a17f https://github.com/NixOS/nixos-hardware https://nix.dev/manual/nix/2.23/language/builtins
# Flow: Grapical install first without swap. We'll add swap file later. This way we won't have to touch hardware-configuration.nix at all

{ config, pkgs, lib, ... }:

let
  user = { name = "asarra"; origin = "de"; time = "Europe/Berlin"; language = "en_US.UTF-8"; };
  device = { host = "guardian"; mode = "ondemand"; cores = 12; };
  inherit (lib) mkForce;
  networkXml = pkgs.writeText "libvirt-default-net.xml" ''
    <network>
      <name>default</name>
      <forward mode='nat'/>
      <bridge name='virbr0' stp='on' delay='0'/>
      <ip address='192.168.122.1' netmask='255.255.255.0'>
        <dhcp>
          <range start='192.168.122.2' end='192.168.122.254'/>
        </dhcp>
      </ip>
    </network>
  '';
  mkSystemSimple = { description, exec, preStart ? "", postStop ? "", timeout ? 30 }: { # Helper template
    description = description; # Manual: https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html
    after = [ "network.target" "local-fs.target" ];
    wantedBy = [ "multi-user.target" ];
    preStart = preStart;
    serviceConfig = {
      User = "root";
      ExecStart = exec;
      TimeoutStopSec = timeout;
    };
    postStop = postStop;
  };
in
{
  imports = [ ./hardware-configuration.nix ]; # autogenerated

  boot = {
    loader = { # Bootloader
      efi.canTouchEfiVariables = true;
      timeout = 5;
      grub = { # GRUB 2 > Systemd-boot
        enable = true;
        efiSupport = true;
        devices = ["nodev"];
        configurationLimit = 3;
        # More entries
        useOSProber = true;
        memtest86.enable = true;
        extraEntries = ''
            menuentry "Reboot" { reboot }
            menuentry "Power off" { halt }
            menuentry "BIOS" { fwsetup }
        '';
      };
    };

    # Kernel
    kernelPackages = pkgs.linuxPackages_latest;
    kernelParams = [ "vfio-pci.ids=10de:1e84,10de:10f8,10de:1ad8,10de:1ad9" "amd_iommu=on" "iommu=pt" ] ++ [ "quiet" ] ++ [ "zswap.enabled=1" "zswap.max_pool_percent=25" "zswap.shrinker_enabled=1" ]; # https://www.kernel.org/doc/Documentation/admin-guide/kernel-parameters.txt # https://ryantm.github.io/nixpkgs/functions/library/lists
    kernelModules = [ "vfio_pci" "vfio" "vfio_iommu_type1" ] ++ config.boot.initrd.availableKernelModules ++ config.boot.initrd.kernelModules; # See: https://github.com/triton/triton
    kernel.sysctl = { "vm.swappiness" = 40; "vm.page-cluster" = 2; }; # swap specific kernel tunables
    blacklistedKernelModules = [ "nvidia" "nouveau" "nvidia_drm" "nvidia_modeset" "ucsi_ccg" ];
    initrd.kernelModules = [ "vfio_pci" "vfio_iommu_type1" "vfio" ];
    initrd.verbose = false;
  };

  swapDevices = mkForce [{ device = "/swapfile"; size = 8192; }];
  powerManagement.cpuFreqGovernor = device.mode; # powersave, performance, ondemand

  networking = {
    hostName = device.host;
    networkmanager.enable = true; # Console: nmcli and nmtui
    useDHCP = mkForce true;
    nameservers = [ "9.9.9.9" "1.1.1.1" ]; # dns
    firewall = {
      allowPing = true;
      allowedTCPPorts = [ 2222 ];
      trustedInterfaces = [ "virbr0" ];
    };
  };

  # Time zone, internationalisation and console mapping
  time.timeZone = user.time;
  i18n.defaultLocale = user.language;
  console.keyMap = user.origin;

  users = {
    users."${user.name}" = {
      isNormalUser = true;
      description = user.name;
      extraGroups = [ "networkmanager" "wheel" "libvirtd" ];
      home = "/home/${user.name}";
    };
  };

  programs = {
    mtr.enable = true; # installs network diagnostic tool
    virt-manager.enable = true; # installs virtualisation client
  };

  environment.systemPackages = with pkgs; [ git btop fastfetch ];

  services.openssh = {
    enable = true;
    openFirewall = true;
    settings = {
      PasswordAuthentication = true;
      PermitRootLogin = "yes";
      MaxAuthTries = 3;
      PerSourcePenalties = "crash:3600s authfail:3600s max:86400s";
    };
  };

  virtualisation = {
    #docker = { # Installs docker and sets it up
    #  enable = false; # https://wiki.nixos.org/wiki/Docker#Rootless_Docker
    #  rootless.enable = true;
    #  rootless.setSocketVariable = true;
    #  rootless.daemon.settings.data-root = "~/.local/share/docker"; # https://discourse.nixos.org/t/rootless-docker-systemd-resolved-and-dns-inside-containers/47030/4
    #};

    libvirtd = {
      enable = true; # If you cannot activate the "default" internet, reboot and try it again with virsh # https://bbs.archlinux.org/viewtopic.php?id=284089
      onBoot = "start";
      qemu = {
        runAsRoot = true;
        swtpm.enable = true; # TPM emulation support
        ovmf.enable = true;  # UEFI support
        ovmf.packages = [ pkgs.OVMFFull.fd ];
      };
    };
  };

  systemd = {
    services = { # https://discourse.nixos.org/t/screen-locker-crashing/33510
      systemd-logind.restartIfChanged = false; # SDDM and lightdm screen locker crash fix
      NetworkManager.restartIfChanged = false;

      systemd.services.libvirt-init-network = {
        description = "Declarative Libvirt default network builder";
        after = [ "libvirtd.service" ];
        requires = [ "libvirtd.service" ];
        wantedBy = [ "multi-user.target" ];
        serviceConfig = {
          Type = "oneshot";
          RemainAfterExit = true;
          ExecStart = pkgs.writeShellScript "init-libvirt-net" ''
            # Prevent duplicate errors by silently checking existing networks
            if ${pkgs.libvirt}/bin/virsh net-info default >/dev/null 2>&1; then
              ${pkgs.libvirt}/bin/virsh net-destroy default || true
              ${pkgs.libvirt}/bin/virsh net-undefine default || true
            fi
            
            # Build network from the strict declarative script block
            ${pkgs.libvirt}/bin/virsh net-define ${networkXml}
            ${pkgs.libvirt}/bin/virsh net-start default
            ${pkgs.libvirt}/bin/virsh net-autostart default
          '';
        };
      };

      colt-vm = mkSystemSimple {
        description = "Colt VM";
        preStart = ''
          mkdir -p /var/lib/my-vms
          [ -f /var/lib/my-vms/colt-disk.qcow2 ] || ${pkgs.qemu_kvm}/bin/qemu-img create -f qcow2 /var/lib/my-vms/colt-disk.qcow2 50G
          [ -f /var/lib/my-vms/coreos.iso ] || ${pkgs.curl}/bin/curl -L -o /var/lib/my-vms/coreos.iso https://github.com/asarra/colt/releases/download/latest/coreos.iso

          # TAP interface for VM IP
          if ! ${pkgs.iproute2}/bin/ip link show colt-tap >/dev/null 2>&1; then
            ${pkgs.iproute2}/bin/ip tuntap add dev colt-tap mode tap user asarra
            ${pkgs.iproute2}/bin/ip link set colt-tap master virbr0
            ${pkgs.iproute2}/bin/ip link set colt-tap up
          fi
        '';
        exec = ''
          ${pkgs.qemu_kvm}/bin/qemu-system-x86_64 \
            -enable-kvm -m 8G -smp 8 -vga none -nographic -cpu max \
            -device pcie-root-port,id=p \
            -drive file=/var/lib/my-vms/colt-disk.qcow2,if=virtio \
            -drive file=/var/lib/my-vms/coreos.iso,media=cdrom \
            -netdev tap,id=net0,ifname=colt-tap,script=no,downscript=no -device virtio-net-pci,netdev=net0 \
            -device vfio-pci,host=26:00.0,bus=p,multifunction=on \
            -device vfio-pci,host=26:00.1,bus=p,addr=00.1 \
            -device vfio-pci,host=26:00.2,bus=p,addr=00.2 \
            -device vfio-pci,host=26:00.3,bus=p,addr=00.3 \
            -serial mon:stdio \
            -append "console=ttyS0,115200n8"
        '';
        postStop = ''
          ${pkgs.iproute2}/bin/ip link delete colt-tap || true
        '';
        };
    };
  };

  nix = {
    optimise.automatic = true;
    gc.automatic = true; # automatic garbage collection
    gc.dates = "weekly";
    gc.options = "--delete-older-than 7d";
    settings = {
      auto-optimise-store = true; # finds duplicates and saves space
      cores = device.cores; # make -jX from Gentoo # https://github.com/NixOS/nix/issues/1127#issuecomment-412176841
      substituters = [ "https://nix-community.cachix.org" "https://cache.nixos.org/"]; # cache URLs of pre-built package binaries
      trusted-public-keys = [ "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=" ];
    };
  };

  security = {
    protectKernelImage = true;
    lockKernelModules = true;
    apparmor.enable = true;
    forcePageTableIsolation = true; # against meltdown and spectre attacks
    virtualisation.flushL1DataCache = "always";
  };

  system = {
    stateVersion = "24.05"; # Did you read the comment?
    nixos.tags = [ "" ]; # Adds a suffix to the generation label in GRUB. Think of this as a message in a git commit.
    autoUpgrade.enable = true;
    autoUpgrade.channel = "https://channels.nixos.org/nixos-24.05";
  };
}
