# Note: I refuse to use flake.nix and home manager.
# Recover fix tip: boot into live iso, lsblk, sudo nixos-enter --root <Mounted_Device_Path>, su - asarra, (commands), exit
# Gems: https://github.com/gianarb/dotfiles/tree/12ab8fa01d3d8efd0e96f7287a2447df3013a17f https://github.com/NixOS/nixos-hardware https://nix.dev/manual/nix/2.23/language/builtins
# Flow: Grapical install first without swap. We'll add swap file later. This way we won't have to touch hardware-configuration.nix at all

{ config, pkgs, lib, ... }:

let
  user = { name = "asarra"; origin = "de"; time = "Europe/Berlin"; language = "en_US.UTF-8"; };
  device = { host = "guardian"; mode = "ondemand"; cores = 12; };
  inherit (lib) mkForce;
  mkSystemSimple = { description, exec, preStart ? "", postStop ? "", timeout ? 30 }: { # Helper template
    description = description; # Manual: https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html
    after = [ "libvirtd.service" "network-online.target" ];
    requires = [ "libvirtd.service" ];
    wantedBy = [ "multi-user.target" ];
    preStart = preStart;
    path = with pkgs; [ libvirt virt-manager qemu_kvm curl bash coreutils ];
    serviceConfig = {
      User = "root";
      ExecStart = exec;
      TimeoutStopSec = timeout;
      Type = "oneshot";
    };
    postStop = postStop;
  };
in
{
  imports = [ ./hardware-configuration.nix ]; # autogenerated

  boot = {
    loader = { # Bootloader
      efi.canTouchEfiVariables = true;
      timeout = 5;
      grub = { # GRUB 2 > Systemd-boot
        enable = true;
        efiSupport = true;
        devices = ["nodev"];
        configurationLimit = 3;
        # More entries
        useOSProber = true;
        memtest86.enable = true;
        extraEntries = ''
            menuentry "Reboot" { reboot }
            menuentry "Power off" { halt }
            menuentry "BIOS" { fwsetup }
        '';
      };
    };

    # Kernel
    kernelPackages = pkgs.linuxPackages_latest;
    kernelParams = [ "vfio-pci.ids=10de:1e84,10de:10f8,10de:1ad8,10de:1ad9" "amd_iommu=on" "iommu=pt" ] ++ [ "quiet" ] ++ [ "zswap.enabled=1" "zswap.max_pool_percent=25" "zswap.shrinker_enabled=1" ]; # https://www.kernel.org/doc/Documentation/admin-guide/kernel-parameters.txt # https://ryantm.github.io/nixpkgs/functions/library/lists
    kernelModules = [ "vfio_pci" "vfio" "vfio_iommu_type1" ] ++ config.boot.initrd.availableKernelModules ++ config.boot.initrd.kernelModules; # See: https://github.com/triton/triton
    kernel.sysctl = { "vm.swappiness" = 40; "vm.page-cluster" = 2; }; # swap specific kernel tunables
    blacklistedKernelModules = [ "nvidia" "nouveau" "nvidia_drm" "nvidia_modeset" "ucsi_ccg" ];
    initrd.kernelModules = [ "vfio_pci" "vfio_iommu_type1" "vfio" ];
    initrd.verbose = false;
  };

  swapDevices = mkForce [{ device = "/swapfile"; size = 8192; }];
  powerManagement.cpuFreqGovernor = device.mode; # powersave, performance, ondemand

  networking = {
    hostName = device.host;
    networkmanager.enable = true; # Console: nmcli and nmtui
    useDHCP = mkForce true;
    nameservers = [ "9.9.9.9" "1.1.1.1" ]; # dns
    firewall = {
      allowPing = true;
      allowedTCPPorts = [ 2222 ];
      trustedInterfaces = [ "virbr0" ];
    };
    nftables.enable = true; # necessary for the VM network
  };

  # Time zone, internationalisation and console mapping
  time.timeZone = user.time;
  i18n.defaultLocale = user.language;
  console.keyMap = user.origin;

  users = {
    users."${user.name}" = {
      isNormalUser = true;
      description = user.name;
      extraGroups = [ "networkmanager" "wheel" "libvirtd" ];
      home = "/home/${user.name}";
    };
  };

  programs = {
    mtr.enable = true; # installs network diagnostic tool
    virt-manager.enable = true; # installs virtualisation client
  };

  environment.systemPackages = with pkgs; [ git btop fastfetch ];

  services.openssh = {
    enable = true;
    openFirewall = true;
    settings = {
      PasswordAuthentication = true;
      PermitRootLogin = "yes";
      MaxAuthTries = 3;
      PerSourcePenalties = "crash:3600s authfail:3600s max:86400s";
    };
  };

  virtualisation = {
    #docker = { # Installs docker and sets it up
    #  enable = false; # https://wiki.nixos.org/wiki/Docker#Rootless_Docker
    #  rootless.enable = true;
    #  rootless.setSocketVariable = true;
    #  rootless.daemon.settings.data-root = "~/.local/share/docker"; # https://discourse.nixos.org/t/rootless-docker-systemd-resolved-and-dns-inside-containers/47030/4
    #};

    libvirtd = {
      enable = true; # If you cannot activate the "default" internet, reboot and try it again with virsh # https://bbs.archlinux.org/viewtopic.php?id=284089
      onBoot = "start";
      onShutdown = "shutdown";
      qemu.runAsRoot = true;
    };
  };

  systemd = {
    services = { # https://discourse.nixos.org/t/screen-locker-crashing/33510
      systemd-logind.restartIfChanged = false; # SDDM and lightdm screen locker crash fix
      NetworkManager.restartIfChanged = false;

      deploy-colt-vm = mkSystemSimple {
        description = "Automatic deployment of colt-vm via deploy.sh";
        after = [ "libvirtd.service" "network-online.target" ];
        requires = [ "libvirtd.service" ];
        exec = "${pkgs.bash}/bin/bash /etc/nixos/deploy.sh";
        timeout = 300; 
      };
    };
  };

  nix = {
    optimise.automatic = true;
    gc.automatic = true; # automatic garbage collection
    gc.dates = "weekly";
    gc.options = "--delete-older-than 7d";
    settings = {
      auto-optimise-store = true; # finds duplicates and saves space
      cores = device.cores; # make -jX from Gentoo # https://github.com/NixOS/nix/issues/1127#issuecomment-412176841
      substituters = [ "https://nix-community.cachix.org" "https://cache.nixos.org/"]; # cache URLs of pre-built package binaries
      trusted-public-keys = [ "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=" ];
    };
  };

  security = {
    protectKernelImage = true;
    apparmor.enable = true;
    forcePageTableIsolation = true; # against meltdown and spectre attacks
    virtualisation.flushL1DataCache = "always";
  };

  system = {
    stateVersion = "24.05"; # Did you read the comment?
    nixos.tags = [ "" ]; # Adds a suffix to the generation label in GRUB. Think of this as a message in a git commit.
    autoUpgrade.enable = true;
    autoUpgrade.channel = "https://channels.nixos.org/nixos-24.05";
  };
}
